In [2]:
import numpy as np

In [4]:
a = np.arange(16) ** 2
print(a)

[  0   1   4   9  16  25  36  49  64  81 100 121 144 169 196 225]


In [16]:
m = a.reshape(4, 4)
print(m)

[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]
 [144 169 196 225]]


In [18]:
print(m.T) # matriz transposta

[[  0  16  64 144]
 [  1  25  81 169]
 [  4  36 100 196]
 [  9  49 121 225]]


In [19]:
np.dot(m, [3, 2, 1, 0]) # produto de matrizes

array([  6, 134, 454, 966])

In [21]:
np.linalg.eigvals(m) #  matriz nos seus valores próprios

array([ 3.65926730e+02, -1.75236436e+01,  1.59691356e+00, -2.13149551e-14])

In [22]:
linha0 = ['00', '01', '02', '03']
linha1 = ['10', '11', '12', '13']
linhas = [linha0, linha1]
np.array(linhas)

array([['00', '01', '02', '03'],
       ['10', '11', '12', '13']], dtype='<U2')

In [33]:
z = np.zeros((3, 5))
print(z)
print('(n° de linhas, n° de colunas): ', z.shape)
print('n° de dimenões:', z.ndim) 

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
(n° de linhas, n° de colunas):  (3, 5)
n° de dimenões: 2


In [39]:
z = np.ones((2, 3, 2))
print(z)
print('(n° de linhas, n° de colunas, n° de matrizes): ', z.shape)
print('n° de dimenões:', z.ndim) 

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]
(n° de linhas, n° de colunas, n° de matrizes):  (2, 3, 2)
n° de dimenões: 3


In [59]:
np.full(3, 1.5)

array([1.5, 1.5, 1.5])

In [60]:
np.random.random(3) # valores aleatorios entre 0 e 1

array([0.42536794, 0.25136474, 0.62359064])

In [40]:
np.eye(3) # matriz identidade

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [41]:
np.diag([10, 20, 30]) # matriz diagonal

array([[10,  0,  0],
       [ 0, 20,  0],
       [ 0,  0, 30]])

In [77]:
a0 = np.arange(10, 101, 10)
a1 = a0.reshape(2, 5)
print(a0)
print(a1)

[ 10  20  30  40  50  60  70  80  90 100]
[[ 10  20  30  40  50]
 [ 60  70  80  90 100]]


In [80]:
a0[4], a1[0, -1]

(50, 50)

In [73]:
a0[[True, False, False, True, False, False, True, False, False, True]]

array([ 0, 30, 60, 90])

In [70]:
a0[a0 > 40]

array([50, 60, 70, 80, 90])

In [83]:
# apenas os impares entre 0 a 14
a2 = np.arange(15)
a2[a2 % 2 != 0]

array([ 1,  3,  5,  7,  9, 11, 13])

In [96]:
a = np.arange(60)
a = a[a % 10 <= 5]
a = a.reshape((6, 6))
a

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [98]:
a[0, 3:5]

array([3, 4])

In [99]:
a[4:, 4:]

array([[44, 45],
       [54, 55]])

In [100]:
a[:, 2]

array([ 2, 12, 22, 32, 42, 52])

In [101]:
a[2::2, ::2]

array([[20, 22, 24],
       [40, 42, 44]])

In [102]:
a[(0, 1, 2, 3, 4), (1, 2, 3, 4, 5)]

array([ 1, 12, 23, 34, 45])

In [103]:
a[3:, [0,2,5]]

array([[30, 32, 35],
       [40, 42, 45],
       [50, 52, 55]])

In [104]:
mask = np.array([1, 0, 1, 0, 0, 1], dtype=bool)
a[mask, 2]

array([ 2, 22, 52])

In [115]:
np.array([0, 10, 20, 30]).reshape(4, 1) * np.arange(3) # broadicasting

array([[ 0,  0,  0],
       [ 0, 10, 20],
       [ 0, 20, 40],
       [ 0, 30, 60]])

In [117]:
np.matrix([[0,1,2], [3,4,5]])

matrix([[0, 1, 2],
        [3, 4, 5]])

In [134]:
a2 = np.array([[5, 4, 3], [2, 1, 0]])
a2

array([[5, 4, 3],
       [2, 1, 0]])

In [127]:
print(a2.sum(), a2.sum(axis=0), a2.sum(axis=1), sep=' | ')

15 | [7 5 3] | [12  3]


In [128]:
print(a2.mean(), a2.mean(axis=0), a2.mean(axis=1), sep=' | ')

2.5 | [3.5 2.5 1.5] | [4. 1.]


In [129]:
print(a2.max(), a2.max(axis=0), a2.max(axis=1), sep=' | ')

5 | [5 4 3] | [5 2]


In [130]:
print(a2.argmax(), a2.argmax(axis=0), a2.argmax(axis=1), sep=' | ')

0 | [0 0 0] | [0 0]


In [132]:
print(a2.min(), a2.min(axis=0), a2.min(axis=1), sep=' | ')

0 | [2 1 0] | [3 0]


In [133]:
print(a2.argmin(), a2.argmin(axis=0), a2.argmin(axis=1), sep=' | ')

5 | [1 1 1] | [2 2]


In [138]:
nomes = np.array(['Ana', 'Rui', 'Ze', 'To', 'Rita'])
notas = np.random.randint(10, 20, 5)
notas

array([14, 10, 14, 12, 11])

In [139]:
np.sort(notas)

array([10, 11, 12, 14, 14])

In [140]:
np.argsort(notas)

array([1, 4, 3, 0, 2], dtype=int64)

In [142]:
# redicionamento - não é necessário repassar a dminensão da matriz
x = np.array([10, 11, 12, 13, 14, 15])
x.reshape(2, 3)

array([[10, 11, 12],
       [13, 14, 15]])

In [143]:
x.reshape(-1, 3)

array([[10, 11, 12],
       [13, 14, 15]])

In [144]:
x.reshape(2, -1)

array([[10, 11, 12],
       [13, 14, 15]])